const express = require('express')
const app = express()
app.put('/message/:id', function(req, res) {
    // res.render('index', {date: new Date().toDateString()})
    res.end(require('crypto')
            .createHash('sha1')
            .update(new Date().toDateString() + req.params.id)
            .digest('hex'))
})
app.listen(process.argv[2])